### PR TITLE
Include PHP8.0 and PHP8.1 in the CI matrix

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Comment by bytestream** [comment]
Unfortunately it's not that simple :p

**Comment by ChristophWurst** [comment]
Seeing what fails is the first step :wink:

**Comment by bytestream** [comment]
I'm not sure how much of horde nextcloud is actually using, but if you're only using the imap client and just want to see the test output on php 8/8.1 then have a look at my forks e.g. https://github.com/bytestream/Mail/

**Comment by ChristophWurst** [comment]
We use it for IMAP mainly https://github.com/nextcloud/mail/blob/main/composer.json#L30-L43

Until 8.0 everything ran really well. But 8.1 is pretty much unusable for us right now.

https://github.com/nextcloud/mail/blob/main/composer.json#L30-L43 and friends make it look like "just" adding 8.x to the tests will be a tedious job.

I'll have a look at your forks. Thanks a lot!

**Comment by bytestream** [comment]
I can confirm that it is a tedious job :joy: 

https://packagist.org/packages/bytestream/horde-imap-client "and friends" are all tested and passing on 8.0 and 8.1. I just haven't fixed any of the deprecation notices.

The changes I made are also not really possible to send back upstream, as I avoided updating `horde/test` as the number of libraries that needing to be updated was just constantly growing to like 100+. Ralf Lang is/was working on getting all the horde libraries updated correctly for Horde 6 - I just couldn't wait that long, or rely on his forks as they kept being rebased.

**Comment by ChristophWurst** [comment]
> https://packagist.org/packages/bytestream/horde-imap-client "and friends" are all tested and passing on 8.0 and 8.1. I just haven't fixed any of the deprecation notices.

A very quick test confirms that your packages work with our application. Awesome! Nevertheless I'll have to bring the ManageSieve and SMTP packages over to packagist as well.

If I look at https://github.com/bytestream/Mime/compare/7f6d0aaea1a1f194f46ac4a0428b539df11b46e1..master then it's not too crazy to migrate one package. I might just give that a go.

FYI I found a little stray dependency at https://github.com/bytestream/Mime/blob/9511e92d7e23d7e0c5ec3932cb9b7e7b11d97066/lib/Horde/Mime/Part.php#L1317. The NLS package is only used there but not an explicit dependency of composer.json.

If that works I'll send my deprecation patches to your forks :)

**Comment by bytestream** [comment]
> FYI I found a little stray dependency at https://github.com/bytestream/Mime/blob/9511e92d7e23d7e0c5ec3932cb9b7e7b11d97066/lib/Horde/Mime/Part.php#L1317. The NLS package is only used there but not an explicit dependency of composer.json.

It was listed under composer suggests list. I'm not sure if there's any code paths that actually result in `getSize()` being used? It should be required rather than suggests if so.

I've added it https://packagist.org/packages/bytestream/horde-nls

**Pull request closed without merging**
